// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWuv84kvK88fjo6MizyIru04mEp3-5ekE',
    appId: '1:280437545769:web:007d159460d231d61bb538',
    messagingSenderId: '280437545769',
    projectId: 'flutterkel1',
    authDomain: 'flutterkel1.firebaseapp.com',
    databaseURL: 'https://flutterkel1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterkel1.firebasestorage.app',
    measurementId: 'G-2GDEMQWZ4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9tThoDh12GBExg8wlA57orOAmcFW2fk0',
    appId: '1:280437545769:android:9a597ab1a899b6131bb538',
    messagingSenderId: '280437545769',
    projectId: 'flutterkel1',
    databaseURL: 'https://flutterkel1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterkel1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGF1kExGGVkDMOiiK9vHGbZymGFMHmhrA',
    appId: '1:280437545769:ios:a62505e6446b087d1bb538',
    messagingSenderId: '280437545769',
    projectId: 'flutterkel1',
    databaseURL: 'https://flutterkel1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterkel1.firebasestorage.app',
    iosBundleId: 'com.example.testingPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGF1kExGGVkDMOiiK9vHGbZymGFMHmhrA',
    appId: '1:280437545769:ios:a62505e6446b087d1bb538',
    messagingSenderId: '280437545769',
    projectId: 'flutterkel1',
    databaseURL: 'https://flutterkel1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterkel1.firebasestorage.app',
    iosBundleId: 'com.example.testingPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWuv84kvK88fjo6MizyIru04mEp3-5ekE',
    appId: '1:280437545769:web:4eef3c164e7b60a31bb538',
    messagingSenderId: '280437545769',
    projectId: 'flutterkel1',
    authDomain: 'flutterkel1.firebaseapp.com',
    databaseURL: 'https://flutterkel1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterkel1.firebasestorage.app',
    measurementId: 'G-9SHGQQF5GK',
  );
}
